# Generated by Django 3.0.3 on 2020-02-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20200229_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='time',
        ),
    ]
